server.port=8081
#druid
spring.datasource.url=jdbc:mysql://localhost:3306/wego?characterEncoding=utf-8&serverTimezone=GMT%2B8
spring.datasource.username=root
spring.datasource.password=xiaopangpang6666
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
spring.datasource.filters=stat,wall
spring.datasource.initialSize=100
spring.datasource.minIdle=500
spring.datasource.maxActive=1000
## ���û�ȡ���ӵȴ���ʱ��ʱ��
spring.datasource.maxWait=60000
## ���ü����òŽ���һ�μ�⣬�����Ҫ�رյĿ������ӣ���λ�Ǻ���
spring.datasource.timeBetweenEvictionRunsMillis=60000
## ����һ�������ڳ�����С�����ʱ�䣬��λ�Ǻ���
spring.datasource.minEvictableIdleTimeMillis=25200000
spring.datasource.validationQuery=SELECT 'x'  
spring.datasource.testWhileIdle=false
spring.datasource.testOnBorrow=false
spring.datasource.testOnReturn=false
spring.datasource.poolPreparedStatements=true
spring.datasource.maxPoolPreparedStatementPerConnectionSize=20
#�����շ�ӳ��
mybatis.configuration.map-underscore-to-camel-case=true
#redis
spring.redis.host=localhost
spring.redis.port=6379
spring.redis.timeout=1000
spring.redis.jedis.pool.max-active=1000
spring.redis.jedis.pool.max-idle=800
spring.redis.jedis.pool.min-idle=500
spring.redis.jedis.pool.max-wait=500
#���õ�����Github��¼�������Ϣ
#github.oauth.client-id=fff4de0f158b273ab1f0
#github.oauth.client-secret=e68c1b7c8d49fb31a3685048906fb601a7ea09da
#github.oauth.callback=http://localhost:8082/oauth/githubLogin
#��������ʹ�õĵ�����github��¼�������Ϣ
github.oauth.client-id=c98b1c698635496d6b8e
github.oauth.client-secret=69e888393fdfec844a1894db6a8e3624e777cb2d
github.oauth.callback=http://38617112yi.zicp.vip/oauth.githubLogin
github.oauth.code-url=https://github.com/login/oauth/authorize
github.oauth.token-url=https://github.com/login/oauth/access_token
github.oauth.user-url=https://api.github.com/user
#����QQ��¼�������Ϣ
qq.oauth.app-id=101944926
qq.oauth.app-key=7914276030f202292e7df758a1b825c6
#����es���
spring.data.elasticsearch.cluster-name=elasticsearch-cluster
spring.data.elasticsearch.cluster-nodes=localhost:9300
#������־����
logging.level.root=INFO
logging.level.com.jd.wego.dao=DEBUG
#ʹ����ţ�����洢ͼƬ����
qiniuyun.AccessKey=pZQHRPGQcHbonZkHxjqbIiZ1kHVjKC3aQN_gwyxJ
qiniuyun.SecretKey=KIE1hdGOUEk8fEnTN1Jt0kQ31mlxy9CEar5LB_Tw
qiniuyun.Bucket=images-storage-wego
qiniuyun.domain.name=http://wegocoder.top



